// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Nide2petyzrrZ8VnKVqPlCio393o2Hw',
    appId: '1:440291488110:web:5198eafb7f6ab8f6f1917f',
    messagingSenderId: '440291488110',
    projectId: 'brazo-robot-cca62',
    authDomain: 'brazo-robot-cca62.firebaseapp.com',
    storageBucket: 'brazo-robot-cca62.firebasestorage.app',
    measurementId: 'G-Y5E8FK68TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3oBYRH2ksIuvMDRwVTyDvKJOHB98CIok',
    appId: '1:440291488110:android:d54e8632419c0721f1917f',
    messagingSenderId: '440291488110',
    projectId: 'brazo-robot-cca62',
    storageBucket: 'brazo-robot-cca62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8Sa8ipO5JiE_9plazNjqpDtJxOIpNdI',
    appId: '1:440291488110:ios:5bbf650e292c40a0f1917f',
    messagingSenderId: '440291488110',
    projectId: 'brazo-robot-cca62',
    storageBucket: 'brazo-robot-cca62.firebasestorage.app',
    iosBundleId: 'com.example.robot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8Sa8ipO5JiE_9plazNjqpDtJxOIpNdI',
    appId: '1:440291488110:ios:5bbf650e292c40a0f1917f',
    messagingSenderId: '440291488110',
    projectId: 'brazo-robot-cca62',
    storageBucket: 'brazo-robot-cca62.firebasestorage.app',
    iosBundleId: 'com.example.robot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Nide2petyzrrZ8VnKVqPlCio393o2Hw',
    appId: '1:440291488110:web:184b8aa07e0c0d43f1917f',
    messagingSenderId: '440291488110',
    projectId: 'brazo-robot-cca62',
    authDomain: 'brazo-robot-cca62.firebaseapp.com',
    storageBucket: 'brazo-robot-cca62.firebasestorage.app',
    measurementId: 'G-NBVBPHFENR',
  );
}
